name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Specify your Node.js version here

      - name: Install dependencies with pnpm
        working-directory: ./web  # Set the working directory to 'web'
        run: npm install -g pnpm && pnpm install  # Install pnpm globally if not installed and then use pnpm to install dependencies

      - name: Build frontend with pnpm
        working-directory: ./web  # Set the working directory to 'web'
        run: pnpm run build  # Run the build script using pnpm

      - name: Set Docker tag
        run: echo "DOCKER_TAG=war7ng/aibackend:${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.DOCKER_TAG }}
          context: .
          file: ./Dockerfile
